import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";
import {MainPage} from '../components/MainPage';
import styled from "styled-components";

const Main = styled.div`
  padding: 0 2rem;
`;

export default function App(){
    return(
        <Main className="container" id="tamir">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <MainPage />
            </main>
            <footer className={styles.footer}>
                Powered by OEV Online Dienstleistungen
            </footer>
        </Main>
     )

};




