import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import { GetStaticProps, InferGetStaticPropsType } from 'next';
import { createSwaggerSpec } from 'next-swagger-doc';
import dynamic from 'next/dynamic';
import styles from '../styles/Home.module.css';
import 'swagger-ui-react/swagger-ui.css';
import something from '../public/apis_docs/example.json';

const SwaggerUI = dynamic<{
  spec: any;
}>(import('swagger-ui-react'), { ssr: false });

const Main = styled.div`
  padding: 0 2rem;
`;

export const Documentation = ({ spec }: InferGetStaticPropsType<typeof getStaticProps>) => <SwaggerUI spec={spec} />;

const Home: NextPage = ({ spec }: any) => (
  <Main className="container" id="tamir">
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>
      <p className={styles.description}>
        Get started by editing{' '}
        <code className={styles.code}>pages/index.tsx</code>
      </p>
      <div className={styles.grid}>
        <a href="" className={styles.card}>
          <h2>Doc1 &rarr;</h2>
          <p>Find in-depth information about Next.js features and API.</p>
        </a>
      </div>
      <Documentation spec={spec} />
    </main>
    <footer className={styles.footer}>
      Powered by OEV Online Dienstleistungen
    </footer>
  </Main>
);

export const getStaticProps: GetStaticProps = async () => {
  const spec: Record<string, any> = createSwaggerSpec({
    definition: something.swaggerInformation,
  });

  return {
    props: {
      spec,
    },
  };
};

export default Home;
